[project]
name = "summit2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logfire>=4.3.6",
    "pydantic>=2.11.7",
    "pydantic-ai>=0.8.1",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
]
